### ISSUE TITLE
Fullscreen/Popout buttons hidden

### ISSUE THREAD

**Issue by UnbreakableKid** [leeprky/Lode#4]
**Describe the bug**

When doing screenshare or videocalls, the button to go fullscreen or pop out the video is missing, maybe underneath the floating profile/settings controls. Only workaround is unfocusing the window and popping out

**To Reproduce**

Start a video or screenshare session
Try to go fullscreen or popout video

**Expected behavior**
A button to go fullscreen or pop should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/29483407/116911042-44f83880-ac3e-11eb-90a5-cb06bf742e0f.png)

Should be under here or something
![image](https://user-images.githubusercontent.com/29483407/116911372-b637eb80-ac3e-11eb-9250-3d59c36c6b5e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Client Powercord

**Comment by leeprky** [comment]
Thanks For The Report!

This is now Fixed, https://cdn.discordapp.com/attachments/825845489613930547/838899471928262666/unknown.png
