### ISSUE TITLE
Theme settings React Component Error

### ISSUE THREAD

**Issue by Dazz05** [leeprky/Lode#5]
**Describe the bug**

I tried to change the settings for this theme, but whenever I clicked on the settings button, it shows up "React Component Error" I tried reinstall betterdiscord and discord, and its still the same.

**To Reproduce**
1. Click on settings
2. Click on "Themes"
3. Locate Lode Theme, click on the settings icon.

**Expected behavior**

Shows up the settings tab for lode theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/65452061/117927422-c6ca1f00-b32c-11eb-9d50-4850efc31257.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Client Better Discord
 - Version Better Discord 1.1.0

**Comment by leeprky** [comment]
Doesn't Seem like a Theme Problem
