### ISSUE TITLE
Corner of reply bubble has a square on top of it

### ISSUE THREAD

**Issue by spelled-ayayron** [leeprky/Lode#6]
**Describe the bug**
A block appears at the bottom right corner of reply bubbles.

**To Reproduce**
1. Go to any text channel
2. Find a reply

**Expected behavior**
Rounded corner/speech bubble tail

**Screenshots**
![image](https://user-images.githubusercontent.com/10445573/118472871-32f6ab00-b6be-11eb-93af-ab9f930136ba.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Client: BetterDiscord 1.1.0
 - Version Lode v1.0.6

**Comment by leeprky** [comment]
Fixed In V1.0.7
