### ISSUE TITLE
Broken profile pictures

### ISSUE THREAD

**Issue by KyleIsDork** [leeprky/Lode#7]
**Describe the bug**
Profile pictures, and the user popup, are broken currently

**To Reproduce**
1. Go to any user
2. Click on the expandable popup

**Expected behavior**
Old popup style appears

**Screenshots**
https://ibb.co/1r62bRr - old style
https://ibb.co/CBq1LxK - new and broken

**Comment by leeprky** [comment]
Discord Updated The Modal And With It We Lost Features To Be Able To Do The Old Style Again So I Just Made A Better Looking Version For Quarrel And Ported To Lode

**Comment by thewilloftheshadow** [comment]
Also, the about me is cut off
![image](https://user-images.githubusercontent.com/35580099/121481770-18001980-c992-11eb-81bd-499fbce19aab.png)
